spring.application.name=HelloShop


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# JPA 기본 설정
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 개발 시 create / 운영 시 none 또는 validate
spring.jpa.hibernate.ddl-auto=create   
# SQL 보기
spring.jpa.show-sql=true               
# SQL 예쁘게
spring.jpa.properties.hibernate.format_sql=true   
# SQL에 주석 출력
spring.jpa.properties.hibernate.use_sql_comments=true 

# 로그 출력 수준 설정 (JPA가 찍는 SQL 쿼리를 로그로 확인 가능)
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace

# 패키지에서 @Entity 탐색 (생략 가능, Boot가 자동 스캔)
# spring.jpa.packages-to-scan=jpabook.jpashop.domain

# H2 콘솔 사용 설정 (원하면 브라우저에서 http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
